# -*- coding: utf-8 -*-
"""AASE DATA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7tf1qp-08RXzHcSvK8CTOLRBizJUUqh
"""

pip install tabulate

#pip install ydata-profiling

import itertools
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tabulate import tabulate
import math
import numpy as np
from scipy import stats
from scipy.stats import shapiro
#from ydata_profiling import ProfileReport

df=pd.read_csv('ScreenTime vs MentalWellness.csv')

#profile = ProfileReport(df, title="Data Understanding Report", explorative=True)

# Mostra diretamente no Jupyter
#profile.to_notebook_iframe()

# (Opcional) Guardar o relatório em HTML
#profile.to_file("data_profile_report.html")

estatisticas = df.describe(include='all')
print(tabulate(estatisticas,headers='keys', tablefmt='github'))

def analisar_valores_csv(dataset):
    df = pd.read_csv(dataset)
    resultado = []
    for coluna in df.columns:
        nulos = df[coluna].isnull().sum()
        em_branco = (df[coluna] == '').sum() if df[coluna].dtype == object else 0
        distintos = df[coluna].nunique(dropna=True)
        unicos = (df[coluna].value_counts() == 1).sum()
        duplicados = len(df[coluna]) - df[coluna].nunique(dropna=False)
        resultado.append({
            'Atributo': coluna,
            'Nulos': nulos,
            'Em Branco': em_branco,
            'Distintos': distintos,
            'Únicos': unicos,
            'Duplicados': duplicados
        })
    return pd.DataFrame(resultado)

"""Ver numero de resultadors iguais nas linhas"""

resultado=analisar_valores_csv('ScreenTime vs MentalWellness.csv')
print(tabulate(resultado,headers='keys', tablefmt='github'))

"""Só para verificar se existem colunas duplicadas"""

df.duplicated()

"""Data Preparition ---->Remover Colunas 'Unnamed: 15' e 'user_id'
Verificar valores extremos e inconsistentes(histogramas e boxplots) para outliers
Verificar ortografia e consistência em variáveis categóricas (gender, occupation, work_mode).

limpar colunas do id porque estava a causar erros

---
"""

drop_cols = [c for c in df.columns if c.lower() == 'user_id']
df_clean = df.drop(columns=drop_cols, errors='ignore').copy()

"""Normalizar strings em categóricas (depois tambem)"""

cat_cols = df_clean.select_dtypes(include='object').columns.tolist()
for c in cat_cols:
    df_clean[c] = df_clean[c].astype(str).str.strip()

print("=== TIPOS DE COLUNAS ===")
print(df_clean.dtypes)
print("\n=== PRIMEIRAS LINHAS ===")
display(df_clean.head())

"""Estatísticas descritivas"""

print("\n=== ESTATÍSTICAS NUMÉRICAS ===")
display(df.describe().T)
print("\n=== VALORES ÚNICOS (CATEGÓRICAS) ===")
for c in cat_cols:
    print(f"\n-- {c} --")
    print(df[c].value_counts(dropna=False))

print("\n=== NULOS POR COLUNA ===")
print(df_clean.isna().sum())
print("\n=== LINHAS DUPLICADAS ===")
print("Duplicadas:", df_clean.duplicated().sum())

print("\n=== VALORES ÚNICOS ===")
for c in cat_cols:
    print(f"{c}: {df_clean[c].unique()}")



"""Histogramas com curva"""

num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cols_per_row = 3
rows = (len(num_cols) + cols_per_row - 1) // cols_per_row

fig, axes = plt.subplots(rows, cols_per_row, figsize=(16, 4 * rows))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    sns.histplot(df_clean[col], kde=True, ax=axes[i])
    axes[i].set_title(f'Histograma — {col}')

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.show()

"""Boxplots"""

num_cols = df_clean.select_dtypes(include=['int64', 'float64', 'float32', 'int32']).columns

# Ignorar colunas Unnamed ou sem variação (constantes)
num_cols = [
    col for col in num_cols
    if not col.lower().startswith('unnamed') and df_clean[col].nunique() > 1
]

fig, axes = plt.subplots(rows, cols_per_row, figsize=(16, 3 * rows))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    sns.boxplot(x=df_clean[col], ax=axes[i])
    axes[i].set_title(f'Boxplot — {col}')

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.show()

"""countplot variaveis 2 por 2"""

cols_per_row = 3
rows = (len(cat_cols) + cols_per_row - 1) // cols_per_row

fig, axes = plt.subplots(rows, cols_per_row, figsize=(14, 4 * rows))
axes = axes.flatten()

for i, c in enumerate(cat_cols):
    sns.countplot(x=df_clean[c], ax=axes[i])
    axes[i].set_title(f"Contagem — {c}")
    axes[i].tick_params(axis='x', rotation=45)

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.show()

"""Os outliers IQR são valores atípicos identificados pelo método do intervalo interquartil (IQR), que é uma medida estatística usada para detectar valores muito distantes da maioria dos dados.

O IQR é calculado como a diferença entre o terceiro quartil (Q3) e o primeiro quartil (Q1) de um conjunto de dados ordenados:
I
Q
R
=
Q
3
−
Q
1
IQR=Q3−Q1

Para identificar outliers, usa-se a regra de Tukey:

Valores abaixo de
Q
1
−
1
,
5
×
I
Q
R
Q1−1,5×IQR são considerados outliers inferiores (muito pequenos).

Valores acima de
Q
3
+
1
,
5
×
I
Q
R
Q3+1,5×IQR são outliers superiores (muito grandes).

Estes outliers aparecem como pontos separados do conjunto principal nos gráficos de caixa (boxplots), porque estão fora do intervalo considerado normal para a distribuição dos dados.

Em resumo, o método IQR permite detectar valores discrepantes no dataset que podem influenciar análises e resultados, ajudando a compreender melhor a variabilidade e a dispersão dos dados
"""

outlier_report = {}
for col in num_cols:
    q1, q3 = df_clean[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5*iqr, q3 + 1.5*iqr
    outliers = df_clean[(df_clean[col] < lower) | (df_clean[col] > upper)][col]
    outlier_report[col] = {
        'n_outliers': len(outliers),
        'pct_outliers': 100 * len(outliers) / len(df_clean)
    }
outlier_df = pd.DataFrame(outlier_report).T
print("\n=== RELATÓRIO DE OUTLIERS (IQR) ===")
display(outlier_df)

"""Heatmap correlação"""

corr = df_clean[num_cols].corr()

plt.figure(figsize=(16, 10))
sns.heatmap(corr, cmap='coolwarm', annot=True, fmt=".2f", linewidths=0.5, square=True, cbar_kws={'shrink': 0.8})
plt.title("Matriz de Correlação", fontsize=14, pad=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""Analise Para CATEGORIAS VS CATEGORIAS e tabela com mais frequente para não ficar perdida


Interpertação disto:

“As mulheres trabalham mais em modo remoto do que os homens?”

“O modo híbrido é mais comum entre um género?”
"""

sns.set(style="whitegrid")


cat_cols = df_clean.select_dtypes(include=['object', 'category']).columns.tolist()

pairs = list(itertools.combinations(cat_cols, 2))

max_pairs = 9
pairs = pairs[:max_pairs]

cols_per_row = 3
rows = (len(pairs) + cols_per_row - 1) // cols_per_row

fig, axes = plt.subplots(rows, cols_per_row, figsize=(16, 5 * rows))
axes = axes.flatten()

for i, (x, y) in enumerate(pairs):
    sns.countplot(data=df_clean, x=x, hue=y, ax=axes[i])
    axes[i].set_title(f"{x} vs {y} (Countplot)", fontsize=11)
    axes[i].tick_params(axis='x', rotation=45)
    axes[i].legend(title=y, loc="best", fontsize=8)

for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.show()

#Codigo do HeatMap para não confundir
cols_per_row = 3
rows = (len(pairs) + cols_per_row - 1) // cols_per_row

fig, axes = plt.subplots(rows, cols_per_row, figsize=(16, 5 * rows))
axes = axes.flatten()

for i, (x, y) in enumerate(pairs):
    contingency = pd.crosstab(df_clean[x], df_clean[y], normalize='index') * 100
    sns.heatmap(contingency, cmap="Reds", annot=True, fmt=".1f", ax=axes[i])
    axes[i].set_title(f"{x} vs {y} (Heatmap %)", fontsize=11)
    axes[i].tick_params(axis='x', rotation=45)
    axes[i].tick_params(axis='y', rotation=0)

for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.show()

categorical_summary = {}

for c in cat_cols:
    counts = df_clean[c].value_counts(normalize=True) * 100
    categorical_summary[c] = counts.round(1).to_dict()

for col, dist in categorical_summary.items():
    top_cat = max(dist, key=dist.get)
    top_val = dist[top_cat]
    unique_vals = len(dist)

    print(f"{col}: {unique_vals} categorias.")
    print(f"   Valor mais frequente: '{top_cat}' ({top_val:.1f}%)")

"""Scatterplots com a variavel target-muito mal clean i guess"""

target = 'mental_wellness_index_0_100'
num_cols = [c for c in df_clean.select_dtypes(include=np.number).columns if c != target]

pairs = [(x, target) for x in num_cols]

cols_per_row = 3
rows = (len(pairs) + cols_per_row - 1) // cols_per_row

fig, axes = plt.subplots(rows, cols_per_row, figsize=(15, 4 * rows))
axes = axes.flatten()

for i, (x, y) in enumerate(pairs):
    sns.regplot(x=df_clean[x], y=df_clean[y], ax=axes[i], scatter_kws={'alpha':0.6})
    axes[i].set_title(f'{y} vs {x}', fontsize=10)
    axes[i].tick_params(axis='x', rotation=30)

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.show()

"""Scatterplots — 90 relações ,dificil calcular quantas são"""

import itertools

num_cols = df_clean.select_dtypes(include=np.number).columns.tolist()
pairs = list(itertools.combinations(num_cols, 2))

max_pairs = 15  # muda se quiseres mais
pairs = pairs[:max_pairs]

cols_per_row = 3
rows = (len(pairs) + cols_per_row - 1) // cols_per_row

fig, axes = plt.subplots(rows, cols_per_row, figsize=(15, 4 * rows))
axes = axes.flatten()

for i, (x, y) in enumerate(pairs):
    sns.regplot(x=df_clean[x], y=df_clean[y], ax=axes[i], scatter_kws={'alpha':0.6})
    axes[i].set_title(f'{y} vs {x}', fontsize=9)
    axes[i].tick_params(axis='x', rotation=30)

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.show()

"""Supostamente muito melhor para observar relações entre variaveis"""

sns.pairplot(df_clean[num_cols], kind="reg", diag_kind="kde", plot_kws={'scatter_kws': {'alpha': 0.5}})
plt.suptitle("Relações entre todas as variáveis numéricas", y=1.02)
plt.show()

"""Boxplots categóricas vs targets"""

cat_vs_num = ['work_mode', 'gender', 'occupation']
targets = ['mental_wellness_index_0_100', 'productivity_0_100']
plots = [(c, t) for c in cat_vs_num for t in targets]

cols_per_row = 3
rows = (len(plots) + cols_per_row - 1) // cols_per_row

fig, axes = plt.subplots(rows, cols_per_row, figsize=(14, 4 * rows))
axes = axes.flatten()

for i, (cat, target) in enumerate(plots):
    sns.boxplot(x=df_clean[cat], y=df_clean[target], ax=axes[i])
    axes[i].set_title(f"{target} por {cat}")
    axes[i].tick_params(axis='x', rotation=45)

for j in range(i+1, len(axes)):
    axes[j].set_visible(False)

plt.tight_layout()
plt.show()

num_cols = df_clean.select_dtypes(include=[np.number]).columns

normality_results = []

print("Teste de Shapiro–Wilk (α = 0.05)\n")

for col in num_cols:
    # Teste só se a coluna tiver pelo menos 3 valores válidos
    if df_clean[col].notna().sum() >= 3:
        stat, p = shapiro(df_clean[col].dropna())
        interpretation = "Normal" if p > 0.05 else "Não normal"
        normality_results.append([col, stat, p, interpretation])
        print(f"{col:<35} | p = {p:.4f} → {interpretation}")

# Guardar resultados num DataFrame para referência
df_normality = pd.DataFrame(normality_results, columns=["Variável", "Estatística", "p-valor", "Interpretação"])

display(df_normality)

# Verificar se o target é normal ou não
target_p = df_normality.loc[df_normality["Variável"] == target, "p-valor"].values[0]
if target_p > 0.05:
    print(f"O target '{target}' parece normal (p={target_p:.3f}) — aplicando IQR para outliers.")
else:
    print(f"O target '{target}' NÃO parece normal (p={target_p:.3f}) — manter valores extremos para cenário 1 e cenário 2.")